# Base Image
FROM ubuntu:24.04

# Metadata
LABEL base.image="ubuntu:24.04"
LABEL version="1"
LABEL software="R"
LABEL software.version="0.0.1"
LABEL description="This image provides R with ggplot2, dplyr and bioconductor"
LABEL tags="R"

# Maintainer
MAINTAINER Roberto Vera Alvarez <r78v10a07@gmail.com>

USER root

RUN apt-get update && \
    apt-get install -y apt-utils tzdata software-properties-common dirmngr wget

RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/"

RUN apt-get update && \
    apt-get install -y libxml2-dev libcurl4-gnutls-dev \
                       libhttrack-dev libjsoncpp-dev libssl-dev \
                       r-base r-base-dev r-recommended && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN Rscript --vanilla -e "install.packages('ggplot2', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('dplyr', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('calibrate', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('optparse', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('BiocManager', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('robustbase', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('dendextend', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('rjson', repo='https://cran.r-project.org')" && \
    Rscript --vanilla -e "install.packages('samr', repo='https://cran.r-project.org')"

#RUN Rscript --vanilla -e "BiocManager::install('impute')" && \
#    Rscript --vanilla -e "BiocManager::install('apeglm')" && \
#    Rscript --vanilla -e "BiocManager::install('biomaRt')"
#    Rscript --vanilla -e "BiocManager::install('ChIPQC')"

USER ubuntu
RUN chmod a+rwx /home/ubuntu/

WORKDIR /data/

CMD ["R"]
