# Base Image
FROM ubuntu:18.04

# Metadata
LABEL base.image="ubuntu:18.04"
LABEL version="1"
LABEL software="R"
LABEL software.version="4.10"
LABEL description="This image provides homer with ORG"
LABEL tags="Homer"

# Maintainer
MAINTAINER Roberto Vera Alvarez <r78v10a07@gmail.com>

USER root

ENV URL=http://homer.ucsd.edu/homer/configureHomer.pl
ENV FOLDER=/usr/local

RUN apt-get update && \
    apt-get install -y apt-utils tzdata && \
    apt-get install -y software-properties-common gcc g++ perl wget zip make unzip && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p $FOLDER && \
    cd $FOLDER && \
    wget $URL && \
    perl configureHomer.pl -install homer && \
    perl configureHomer.pl -install ORG

RUN adduser --disabled-password --gecos '' ubuntu
USER ubuntu
RUN chmod a+rwx /home/ubuntu/

WORKDIR /data/

CMD ["/bin/bash"]
