# Base Image
FROM ubuntu:18.04

# Metadata
LABEL base.image="ubuntu:18.04"
LABEL version="1"
LABEL software="R"
LABEL software.version="4.10"
LABEL description="This image provides homer with E_coli, K-12, MG1655 "
LABEL tags="Homer"

# Maintainer
MAINTAINER Roberto Vera Alvarez <r78v10a07@gmail.com>

USER root

ENV URL=http://homer.ucsd.edu/homer/configureHomer.pl
ENV FOLDER=/usr/local

RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y tzdata && \
    apt-get install -y software-properties-common

RUN apt-get update && \
    apt-get install -y gcc g++ perl wget zip make unzip && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p $FOLDER && \
    cd $FOLDER && \
    wget $URL && \
    perl configureHomer.pl -install homer

ENV DST=/tmp
RUN cd $DST
COPY NC_000913.3.fasta NC_000913.3.gff ./
RUN loadGenome.pl -name ecoli_mg1655 -fasta NC_000913.3.fasta -gff NC_000913.3.gff  -org null
WORKDIR /data/

CMD ["/bin/bash"]
